[build]
  functions = "netlify/functions"

[[plugins]]
  package = "@netlify/plugin-functions-install-core"

[build.environment]
  NODE_VERSION = "18"

[[headers]]
  for = "/js/firebase-config.js"
  [headers.values]
    X-Robots-Tag = "noindex"

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"