[build]
  functions = "netlify/functions"

[[plugins]]
  package = "@netlify/plugin-functions-install-core"

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"